name: Convert Py to JSON and call external service to measurement
on: push
jobs:
  convert-and-call:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
    - name: Install dependencies
      run: pip install -r requirements.txt # Archivo de requisitos con los paquetes necesarios
    - name: Delete old JSON files
      run: find . -name '*.json' -delete # Busca y elimina todos los archivos JSON existentes en el repositorio
    - name: Quantum circuit measurement
      run: python convert.py #Realiza la conversión en JSON de los circuitos y realiza la medición
